server:
  port: 8080
  servlet:
    context-path: /aec
spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/aecinfo?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      test-on-borrow: false
      initial-size: 1
      min-idle: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.irving.aecproject.web.dao
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql