server:
  port: 8077
#  servlet:
#    context-path: /aec
spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/aecinfo?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      test-on-borrow: false
      initial-size: 1
      min-idle: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.irving.aecproject.web.dao
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
com:
  irving:
    security:
      social:
        processUrl: /qqLogin
        qq:
          providerId: callback.do
          appId: 100550231
          appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        weixin:
          providerId: weixin
          appId: wxd99431bbff8305a0
          appSecret: 60f78681d063590a469f1b297feff3c4
      CAPTCHA:
#        length: 6
#        width: 100
#        urls: /hello, /user/*, /user
      browser:
        loginPage: /member/toLogin
#        loginType: REDIRECT
        rememberMeDuration: 1800
        signUpUrl: /demo-signup.html